python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText01 > ~/sed_expData/out.uniqueTweets01
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText02 > ~/sed_expData/out.uniqueTweets02
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText03 > ~/sed_expData/out.uniqueTweets03
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText04 > ~/sed_expData/out.uniqueTweets04
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText05 > ~/sed_expData/out.uniqueTweets05
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText06 > ~/sed_expData/out.uniqueTweets06
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText07 > ~/sed_expData/out.uniqueTweets07
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText08 > ~/sed_expData/out.uniqueTweets08
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText09 > ~/sed_expData/out.uniqueTweets09
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText10 > ~/sed_expData/out.uniqueTweets10
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText11 > ~/sed_expData/out.uniqueTweets11
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText12 > ~/sed_expData/out.uniqueTweets12
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText13 > ~/sed_expData/out.uniqueTweets13
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText14 > ~/sed_expData/out.uniqueTweets14
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText15 > ~/sed_expData/out.uniqueTweets15
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText16 > ~/sed_expData/out.uniqueTweets16
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText17 > ~/sed_expData/out.uniqueTweets17
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText18 > ~/sed_expData/out.uniqueTweets18
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText19 > ~/sed_expData/out.uniqueTweets19
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText20 > ~/sed_expData/out.uniqueTweets20
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText21 > ~/sed_expData/out.uniqueTweets21
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText22 > ~/sed_expData/out.uniqueTweets22
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText23 > ~/sed_expData/out.uniqueTweets23
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText24 > ~/sed_expData/out.uniqueTweets24
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText25 > ~/sed_expData/out.uniqueTweets25
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText26 > ~/sed_expData/out.uniqueTweets26
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText27 > ~/sed_expData/out.uniqueTweets27
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText28 > ~/sed_expData/out.uniqueTweets28
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText29 > ~/sed_expData/out.uniqueTweets29
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText30 > ~/sed_expData/out.uniqueTweets30
python uniqueTweet.py ~/corpus/data_stock201504/word/tweetCleanText31 > ~/sed_expData/out.uniqueTweets31
